const routine={
1:{ko:"가슴 + 삼두",cardio:"천국의 계단 20분",items:[["인클라인 머신 프레스","4","8–10","120초","가슴을 높이고 어깨를 뒤로 고정. 팔꿈치 45도.","🏔️"],["체스트 프레스 머신","3","8–12","120초","어깨가 앞으로 말리지 않게. 팔꿈치 잠금 금지.","⚙️"],["인클라인 덤벨 프레스","3","8–12","120초","내릴 때 2~3초. 윗가슴 옆으로.","🏋️"],["펙덱 플라이","3","12–15","60초","수축 지점 1초 정지.","🪽"],["삼두 푸쉬다운","4","10–15","60초","팔꿈치 고정.","⚡"],["오버헤드 익스텐션","3","12–15","60초","머리 뒤로 충분히 늘리기.","🔩"]]},
2:{ko:"등 + 이두",cardio:"사이클 20분",items:[["친업","4","가능-1","120초","가슴을 바에 가까이. 광배 늘리기.","🦅"],["랫풀다운","4","8–12","120초","팔꿈치를 아래로 꽂는 느낌.","⬇️"],["시티드 케이블 로우","3","10–12","90초","배꼽 방향. 수축 1초.","🚣"],["체스트 서포티드 로우","3","8–12","90초","가슴 패드 고정.","🧱"],["스트레이트 암 풀다운","3","12–15","60초","광배로 바를 허벅지까지.","📐"],["덤벨 컬","3","10–12","60초","팔꿈치 고정.","💪"],["해머컬","3","10–15","60초","엄지가 위.","🔨"]]},
3:{ko:"하체 + 팔",cardio:"런닝머신 30분",items:[["레그컬","4","10–15","75초","햄스트링 접기.","🦵"],["레그익스텐션","4","12–15","75초","상단 1초 정지.","⚙️"],["핵스쿼트","4","8–10","150초","무릎은 발끝 방향.","🏔️"],["레그프레스","4","10–12","150초","무릎 잠그지 않기.","🚀"],["루마니안 데드리프트","3","8–10","150초","엉덩이를 뒤로.","🧲"],["카프레이즈","5","12–20","60초","아래 끝까지 늘리기.","📈"],["케이블 컬","3","12–15","60초","이두만.","💪"],["푸쉬다운","3","12–15","60초","팔꿈치 고정.","⚡"]]},
4:{ko:"어깨 + 팔",cardio:"천국의 계단 20분",items:[["머신 숄더프레스","4","8–10","120초","허리 과신전 금지.","🛡️"],["덤벨 숄더프레스","3","8–12","120초","귀 옆으로 내리기.","🏋️"],["케이블 레터럴 레이즈","4","12–20","60초","5kg 힘들면 몸 기울여 한 팔씩.","📡"],["덤벨 레터럴 레이즈","3","15–20","60초","반동 최소.","🪽"],["리어델트 플라이","4","12–20","60초","팔꿈치 벌리기.","🎯"],["페이스풀","3","15–20","60초","눈높이로 당기기.","🧬"],["해머컬","3","10–15","60초","팔 두께.","🔨"],["오버헤드 익스텐션","3","12–15","60초","삼두 장두.","🔩"]]},
5:{ko:"가슴 + 등 + 팔",cardio:"사이클 20분",items:[["인클라인 머신 프레스","3","8–10","120초","윗가슴.","🏔️"],["펙덱 플라이","3","12–15","60초","가슴 수축.","🪽"],["랫풀다운","3","8–12","120초","광배.","⬇️"],["체스트 서포티드 로우","3","10–12","90초","등 두께.","🧱"],["프리처 컬","3","10–12","60초","반동 금지.","💪"],["삼두 푸쉬다운","3","10–15","60초","끝까지 펴기.","⚡"]]},
6:{ko:"어깨 + 하체 + 팔",cardio:"런닝머신 25분",items:[["덤벨 레터럴 레이즈","4","15–20","60초","측면 펌핑.","🪽"],["리어델트 플라이","4","15–20","60초","후면어깨.","🎯"],["레그프레스","4","10–12","150초","하체 볼륨.","🚀"],["레그컬","3","12–15","75초","햄스트링.","🦵"],["레그익스텐션","3","12–15","75초","대퇴사두.","⚙️"],["해머컬","3","10–15","60초","팔 두께.","🔨"],["오버헤드 익스텐션","3","12–15","60초","삼두 장두.","🔩"]]},
0:{ko:"휴식 / 걷기",cardio:"8,000–10,000보",items:[["걷기","1","30–60분","-","회복 목적.","🚶"],["스트레칭","1","10분","-","광배, 고관절, 햄스트링.","🧘"]]}
};
const $=(s,r=document)=>r.querySelector(s),$$=(s,r=document)=>[...r.querySelectorAll(s)];
const today=()=>new Date().toISOString().slice(0,10);
const get=(k,f)=>{try{return JSON.parse(localStorage.getItem(k))??f}catch{return f}};
const set=(k,v)=>localStorage.setItem(k,JSON.stringify(v));
let day=Number(get("asc7.day",new Date().getDay())),remain=0,timerId=null;
const dayKey=()=>`asc7.check.${today()}.${day}`;

function toast(msg){const t=$("#toast");t.textContent=msg;t.classList.add("show");clearTimeout(window.tt);window.tt=setTimeout(()=>t.classList.remove("show"),1500)}
function xp(n){set("asc7.xp",get("asc7.xp",0)+n)}
function flash(el){if(!el)return;el.classList.add("pulse");setTimeout(()=>el.classList.remove("pulse"),650)}
function route(id){$$(".tab").forEach(b=>b.classList.toggle("active",b.dataset.tab===id));$$(".page").forEach(p=>p.classList.toggle("active",p.id===id))}
function saveProfile(){set("asc7.profile",{
weight:$("#weight").value,sleep:$("#sleep").value,protein:$("#protein").value,water:$("#water").value,
chkCreatine:$("#chkCreatine").checked,chkProtein:$("#chkProtein").checked,chkSkin:$("#chkSkin").checked,chkSteps:$("#chkSteps").checked});render()}
function init(){
["일","월","화","수","목","금","토"].forEach((n,i)=>{let o=document.createElement("option");o.value=i;o.textContent=`${n} · ${routine[i].ko}`;$("#daySelect").appendChild(o)});$("#daySelect").value=day;
$("#daySelect").onchange=e=>{day=+e.target.value;set("asc7.day",day);render()};
$$(".tab").forEach(b=>b.onclick=()=>route(b.dataset.tab));
["weight","sleep","protein","water"].forEach(id=>{$("#"+id).value=get("asc7.profile",{})[id]||"";$("#"+id).oninput=saveProfile});
["chkCreatine","chkProtein","chkSkin","chkSteps"].forEach(id=>{$("#"+id).checked=!!get("asc7.profile",{})[id];$("#"+id).onchange=saveProfile});
$("#saveDay").onclick=saveDay;$("#refreshAria").onclick=()=>{renderAria(true);toast("ARIA 업데이트")};
$("#saveFood").onclick=saveFood;$("#saveJournal").onclick=saveJournal;$("#savePhoto").onclick=savePhoto;$("#stopTimer").onclick=()=>{$("#timer").classList.remove("show");clearInterval(timerId)};
$("#foodMemo").value=get("asc7.food","");$("#journalMemo").value=get("asc7.journal","");
render()
}
function render(){renderWorkout();renderLogs();renderHome();renderAria(false);renderFood();renderJournal();renderPhotos();renderChart();renderCalendar()}
function workoutPct(){const total=routine[day].items.length,done=Object.values(get(dayKey(),{})).filter(Boolean).length;return {total,done,pct:total?Math.round(done/total*100):0}}
function renderHome(){const p=get("asc7.profile",{}),w=+p.weight||0,prot=+p.protein||0,water=+p.water||0,sleep=+p.sleep||0;$("#proteinBar").style.width=Math.min(100,prot/150*100)+"%";$("#waterBar").style.width=Math.min(100,water/3000*100)+"%";if(w){let gp=Math.max(0,Math.min(100,(81-w)/8*100));$("#goalBar").style.width=gp+"%";$("#goalPct").textContent=Math.round(gp)+"%";$("#goalText").textContent=`목표까지 ${(w-73).toFixed(1)}kg`}let wp=workoutPct();$("#workPct").textContent=wp.pct+"%";$("#ring").style.strokeDashoffset=389.6*(1-wp.pct/100);let score=Math.round(wp.pct*.3)+Math.min(20,Math.round(prot/150*20))+Math.min(15,Math.round(water/3000*15))+(sleep>=7?15:Math.round(sleep/7*15));["chkCreatine","chkProtein","chkSkin","chkSteps"].forEach(id=>{if($("#"+id).checked)score+=5});score=Math.min(100,score);$("#score").textContent=score;$("#scoreText").textContent=score>=85?"좋아. 오늘은 흐름이 좋다.":score>=60?"괜찮아. 부족한 미션만 채우자.":"아직 채울 게 많아.";let totalXp=get("asc7.xp",0);$("#level").textContent=Math.floor(totalXp/100)+1;$("#xp").textContent=`${totalXp%100}/100 XP`;$("#streak").textContent=get("asc7.streak",0)+"🔥"}
function renderAria(force){const p=get("asc7.profile",{}),wp=workoutPct();let lines=[`오늘 루틴: ${routine[day].ko}`,`운동 완료율: ${wp.done}/${wp.total} (${wp.pct}%)`];if(+p.sleep&&+p.sleep<6)lines.push("수면 부족: 오늘은 RIR 2 정도로 마무리 추천.");if((+p.protein||0)<120)lines.push("단백질 부족: 프로틴이나 단백질 식사 추가 추천.");if((+p.water||0)<2000)lines.push("수분 부족: 운동 전후 물을 더 챙겨.");let logs=routine[day].items.filter(it=>get("asc7.log."+it[0],{}).date===today()).length;if(logs)lines.push(`오늘 저장한 운동 기록 ${logs}개. 다음 무게 추천에 반영됨.`);if(force)lines.push("업데이트: "+new Date().toLocaleTimeString("ko-KR",{hour:"2-digit",minute:"2-digit"}));$("#ariaHome").textContent=lines[1];}
function renderWorkout(){const s=get(dayKey(),{});$("#workSummary").innerHTML=`${routine[day].ko} · ${workoutPct().done}/${workoutPct().total} 완료 · ${workoutPct().pct}%`;$("#workoutList").innerHTML="";routine[day].items.forEach((it,i)=>{let id="ex"+i,card=document.createElement("article");card.className="exercise"+(s[id]?" done":"");card.innerHTML=`<div class="exTop"><div class="icon">${it[5]}</div><div class="exBody"><h3>${it[0]}</h3><div class="chips"><span class="chip">${it[1]}세트</span><span class="chip">${it[2]}</span><span class="chip">${it[3]}</span></div></div><input type="checkbox" ${s[id]?"checked":""}></div><details><summary>자세</summary>${it[4]}</details><div class="smallBtns">${it[3]!="-"?`<button data-sec="${parseInt(it[3])}">휴식 ${it[3]}</button>`:""}<button data-log="${it[0]}">기록</button></div>`;$("input",card).onchange=e=>{let n=get(dayKey(),{});n[id]=e.target.checked;set(dayKey(),n);if(e.target.checked)xp(3);toast(e.target.checked?"운동 체크 완료":"체크 해제");render()};let tb=$("[data-sec]",card);if(tb)tb.onclick=()=>startTimer(+tb.dataset.sec);$("[data-log]",card).onclick=()=>{route("log");setTimeout(()=>document.querySelector(`[data-name="${CSS.escape(it[0])}"]`)?.scrollIntoView({behavior:"smooth",block:"center"}),50)};$("#workoutList").appendChild(card)})}
function renderLogs(){let box=$("#logList");box.innerHTML="";routine[day].items.forEach(it=>{if(it[3]=="-")return;let name=it[0],d=get("asc7.log."+name,{}),card=document.createElement("article");card.className="logCard";card.dataset.name=name;card.innerHTML=`<h3>${name}</h3><p class="status">${recommend(d)}</p><div class="setgrid"><input class="kg" type="number" step=".5" placeholder="kg" value="${d.kg||""}"><input class="r1" type="number" placeholder="1" value="${d.r1||""}"><input class="r2" type="number" placeholder="2" value="${d.r2||""}"><input class="r3" type="number" placeholder="3" value="${d.r3||""}"></div><button class="btn">저장</button><p class="status">${d.time?`최근 저장 ${d.time}`:"저장 대기 중"}</p>`;$("button",card).onclick=()=>{let nd={kg:$(".kg",card).value,r1:$(".r1",card).value,r2:$(".r2",card).value,r3:$(".r3",card).value,date:today(),time:new Date().toLocaleTimeString("ko-KR",{hour:"2-digit",minute:"2-digit"})};set("asc7.log."+name,nd);xp(8);toast("운동 기록 저장됨");flash(card);render()};box.appendChild(card)})}
function recommend(d){let kg=+d.kg,reps=[+d.r1,+d.r2,+d.r3];if(!kg||reps.some(x=>!x))return"기록하면 추천 표시";if(reps.every(x=>x>=12))return`다음 ${kg+2.5}kg 추천`;if(reps.some(x=>x<8))return`${Math.max(0,kg-2.5)}kg로 낮춰도 됨`;return"현재 무게 유지"}
function saveFood(){set("asc7.food",$("#foodMemo").value);xp(5);toast("Nutrition 저장됨");renderFood();renderHome()}
function renderFood(){$("#foodPreview").textContent=get("asc7.food","")||"저장된 식단 없음";$("#foodMemo").value=get("asc7.food","")}
function saveJournal(){set("asc7.journal",$("#journalMemo").value);xp(5);toast("Journal 저장됨");renderJournal();renderHome()}
function renderJournal(){$("#journalPreview").textContent=get("asc7.journal","")||"저장된 저널 없음";$("#journalMemo").value=get("asc7.journal","")}
function savePhoto(){let file=$("#photoInput").files[0];if(!file){toast("사진을 선택해줘");return}let reader=new FileReader();reader.onload=()=>{let arr=get("asc7.photos",[]);arr.push({date:today(),time:new Date().toLocaleTimeString("ko-KR",{hour:"2-digit",minute:"2-digit"}),memo:$("#photoMemo").value,data:reader.result});set("asc7.photos",arr.slice(-12));$("#photoMemo").value="";$("#photoInput").value="";xp(10);toast("사진 저장됨");renderPhotos();renderHome()};reader.readAsDataURL(file)}
function renderPhotos(){let arr=get("asc7.photos",[]);$("#photoCount").textContent=`${arr.length}개`;$("#photoTimeline").innerHTML=arr.length?"":"저장된 사진 없음";arr.slice().reverse().forEach(p=>{let el=document.createElement("article");el.className="photo";el.innerHTML=`<img src="${p.data}"><div><b>${p.date} ${p.time}</b><p>${p.memo||"메모 없음"}</p></div>`;$("#photoTimeline").appendChild(el)})}
function saveDay(){saveProfile();let arr=get("asc7.days",[]).filter(x=>x!==today());arr.push(today());set("asc7.days",arr);set("asc7.streak",calcStreak(arr));let w=+$("#weight").value;if(w){let ws=get("asc7.weights",[]).filter(x=>x.date!==today());ws.push({date:today(),weight:w});set("asc7.weights",ws.slice(-21))}xp(30);toast("오늘 저장됨");render()}
function calcStreak(arr){let s=new Set(arr),n=0,d=new Date();while(s.has(d.toISOString().slice(0,10))){n++;d.setDate(d.getDate()-1)}return n}
function renderChart(){let arr=get("asc7.weights",[]),c=$("#weightChart");c.innerHTML="";if(!arr.length){c.textContent="체중 저장하면 그래프가 생겨.";return}let vals=arr.map(x=>x.weight),min=Math.min(...vals)-.5,max=Math.max(...vals)+.5;arr.forEach(x=>{let b=document.createElement("div");b.className="chartBar";b.style.height=22+((x.weight-min)/(max-min))*75+"px";b.innerHTML=`<span>${x.weight}</span>`;c.appendChild(b)})}
function renderCalendar(){let arr=new Set(get("asc7.days",[])),c=$("#calendar");c.innerHTML="";let d=new Date();d.setDate(d.getDate()-20);for(let i=0;i<21;i++){let iso=d.toISOString().slice(0,10),el=document.createElement("div");el.className="dayDot"+(arr.has(iso)?" done":"");el.textContent=d.getDate();c.appendChild(el);d.setDate(d.getDate()+1)}}
function startTimer(sec){remain=sec;$("#timer").classList.add("show");clearInterval(timerId);tick();timerId=setInterval(()=>{remain--;tick();if(remain<=0){clearInterval(timerId);toast("휴식 끝")}},1000)}
function tick(){let m=String(Math.floor(remain/60)).padStart(2,"0"),s=String(remain%60).padStart(2,"0");$("#timerText").textContent=`${m}:${s}`}
function renderProgress(){renderChart();renderCalendar()}
if("serviceWorker"in navigator)navigator.serviceWorker.register("./sw.js").catch(()=>{});
init();
