const routine={1:{ko:"가슴 + 삼두",cardio:"천국의 계단 20분",items:[["인클라인 머신 프레스","4","8–10","120초","가슴을 높이고 어깨를 뒤로 고정. 팔꿈치 45도. 손잡이는 윗가슴 라인.","🏔️"],["체스트 프레스 머신","3","8–12","120초","어깨가 앞으로 말리지 않게. 끝에서 팔꿈치 완전 잠금 금지.","⚙️"],["인클라인 덤벨 프레스","3","8–12","120초","내릴 때 2~3초. 윗가슴 옆으로 내리기.","🏋️"],["펙덱 플라이","3","12–15","60초","가슴을 모으는 느낌. 수축 지점 1초 정지.","🪽"],["삼두 푸쉬다운","4","10–15","60초","팔꿈치 고정. 아래에서 삼두 끝까지 조이기.","⚡"],["오버헤드 익스텐션","3","12–15","60초","머리 뒤로 충분히 늘리고 팔꿈치 벌어짐 주의.","🔩"]]},2:{ko:"등 + 이두",cardio:"사이클 20분",items:[["친업","4","가능-1","120초","가슴을 바에 가까이. 내려갈 때 광배를 끝까지 늘려.","🦅"],["랫풀다운","4","8–12","120초","팔꿈치를 아래로 꽂는 느낌. 쇄골 쪽으로 당겨.","⬇️"],["시티드 케이블 로우","3","10–12","90초","허리 젖히지 말고 배꼽 방향. 수축 1초.","🚣"],["체스트 서포티드 로우","3","8–12","90초","가슴 패드 고정. 팔꿈치를 뒤로.","🧱"],["스트레이트 암 풀다운","3","12–15","60초","팔꿈치 고정, 광배로 바를 허벅지까지.","📐"],["덤벨 컬","3","10–12","60초","팔꿈치 고정. 손목 꺾지 않기.","💪"],["해머컬","3","10–15","60초","엄지가 위. 팔 두께와 전완.","🔨"]]},3:{ko:"하체 + 팔",cardio:"런닝머신 30분 · 경사 5 · 속도 5–6",items:[["레그컬","4","10–15","75초","올릴 때 1초 조이고 천천히 내려.","🦵"],["레그익스텐션","4","12–15","75초","상단 1초 정지. 무릎 튕기지 않기.","⚙️"],["핵스쿼트","4","8–10","150초","발 어깨너비, 무릎은 발끝 방향.","🏔️"],["레그프레스","4","10–12","150초","무릎 잠그지 말고 엉덩이 뜨지 않는 깊이.","🚀"],["루마니안 데드리프트","3","8–10","150초","허리 말지 말고 엉덩이를 뒤로.","🧲"],["카프레이즈","5","12–20","60초","아래 끝까지 늘리고 위에서 1초 멈춤.","📈"],["케이블 컬","3","12–15","60초","어깨 개입 없이 이두만.","💪"],["푸쉬다운","3","12–15","60초","팔꿈치 고정.","⚡"]]},4:{ko:"어깨 + 팔",cardio:"천국의 계단 20분",items:[["머신 숄더프레스","4","8–10","120초","손잡이는 귀 옆. 허리 과신전 금지.","🛡️"],["덤벨 숄더프레스","3","8–12","120초","덤벨을 귀 옆으로 내리고 머리 위에서 모아.","🏋️"],["케이블 레터럴 레이즈","4","12–20","60초","5kg가 무거우면 몸을 반대쪽으로 기울여 한 팔씩.","📡"],["덤벨 레터럴 레이즈","3","15–20","60초","반동 최소. 어깨 높이까지만.","🪽"],["리어델트 플라이","4","12–20","60초","팔꿈치를 벌리는 느낌. 승모 개입 줄이기.","🎯"],["페이스풀","3","15–20","60초","눈높이로 당겨 후면어깨와 등상부.","🧬"],["해머컬","3","10–15","60초","팔 두께.","🔨"],["오버헤드 익스텐션","3","12–15","60초","삼두 장두.","🔩"]]},5:{ko:"가슴 + 등 + 팔",cardio:"사이클 20분",items:[["인클라인 머신 프레스","3","8–10","120초","윗가슴 중심.","🏔️"],["펙덱 플라이","3","12–15","60초","가슴 수축 1초.","🪽"],["랫풀다운","3","8–12","120초","광배 넓이.","⬇️"],["체스트 서포티드 로우","3","10–12","90초","등 두께.","🧱"],["프리처 컬","3","10–12","60초","반동 금지.","💪"],["삼두 푸쉬다운","3","10–15","60초","끝까지 펴기.","⚡"]]},6:{ko:"어깨 + 하체 + 팔",cardio:"런닝머신 25분",items:[["덤벨 레터럴 레이즈","4","15–20","60초","어깨 측면 펌핑.","🪽"],["리어델트 플라이","4","15–20","60초","후면어깨.","🎯"],["레그프레스","4","10–12","150초","하체 볼륨.","🚀"],["레그컬","3","12–15","75초","햄스트링.","🦵"],["레그익스텐션","3","12–15","75초","대퇴사두.","⚙️"],["해머컬","3","10–15","60초","팔 두께.","🔨"],["오버헤드 익스텐션","3","12–15","60초","삼두 장두.","🔩"]]},0:{ko:"휴식 / 걷기",cardio:"8,000–10,000보",items:[["걷기","1","30–60분","-","붓기 제거와 회복 목적.","🚶"],["스트레칭","1","10분","-","가슴, 광배, 고관절, 햄스트링.","🧘"]]}};
const $=(s,r=document)=>r.querySelector(s), $$=(s,r=document)=>[...r.querySelectorAll(s)];
const date=()=>new Date().toISOString().slice(0,10);
const get=(k,f)=>{try{return JSON.parse(localStorage.getItem(k))??f}catch{return f}}, set=(k,v)=>localStorage.setItem(k,JSON.stringify(v));
let day=Number(get("asc.day",new Date().getDay())), tid=null, remain=0;
const dayKey=()=>`asc.check.${date()}.${day}`;

function init(){
  const h=new Date().getHours(); $("#greeting").textContent=h<12?"민준, 아침 미션 시작":h<18?"민준, 오늘 루틴 가자":"민준, 오늘도 올라가자";
  ["일","월","화","수","목","금","토"].forEach((n,i)=>{const o=document.createElement("option");o.value=i;o.textContent=`${n} · ${routine[i].ko}`;$("#daySelect").appendChild(o)});$("#daySelect").value=day;
  $("#daySelect").onchange=e=>{day=Number(e.target.value);set("asc.day",day);render()};
  $$(".tab").forEach(b=>b.onclick=()=>route(b.dataset.tab));
  $$("[data-route]").forEach(b=>b.onclick=()=>route(b.dataset.route));
  ["weight","protein","water","sleep"].forEach(id=>{$("#"+id).value=get("asc.profile",{})[id]??"";$("#"+id).oninput=saveProfile});
  ["cCreatine","cProtein","cSkin","cSteps"].forEach(id=>{$("#"+id).checked=!!get("asc.profile",{})[id];$("#"+id).onchange=saveProfile});
  $("#saveMorning").onclick=saveWeight; $("#clearWeights").onclick=()=>{set("asc.weights",[]);drawChart()};
  $("#stopTimer").onclick=()=>{clearInterval(tid);$("#timer").classList.remove("show")};
  render();
}
function route(tab){$$(".tab").forEach(x=>x.classList.toggle("active",x.dataset.tab===tab));$$(".view").forEach(x=>x.classList.toggle("active",x.id===tab))}
function saveProfile(){set("asc.profile",{weight:$("#weight").value,protein:$("#protein").value,water:$("#water").value,sleep:$("#sleep").value,cCreatine:$("#cCreatine").checked,cProtein:$("#cProtein").checked,cSkin:$("#cSkin").checked,cSteps:$("#cSteps").checked});updateMetrics()}
function render(){const r=routine[day];$("#todayKo").textContent=r.ko;$("#todayCardio").textContent=r.cardio;renderWorkout();renderLog();updateProgress();updateMetrics();drawChart()}
function updateMetrics(){const w=Number($("#weight").value), p=Number($("#protein").value)||0, water=Number($("#water").value)||0, sleep=Number($("#sleep").value)||0;$("#proteinBar").style.width=Math.min(100,p/150*100)+"%";$("#waterBar").style.width=Math.min(100,water/3000*100)+"%";if(w){const pct=Math.max(0,Math.min(100,(81-w)/(81-73)*100));$("#goalLine").style.width=pct+"%";$("#goalPercent").textContent=Math.round(pct)+"%";$("#goalText").textContent=`목표까지 ${(w-73).toFixed(1)}kg. 너무 빠른 감량보다 꾸준함 우선.`;$("#weightMsg").textContent=`목표까지 ${(w-73).toFixed(1)}kg`}$("#sleepMsg").textContent=sleep>=7.5?"회복 좋음":"수면 부족이면 강도 90%로"}
function renderWorkout(){const saved=get(dayKey(),{}), wrap=$("#workoutList");wrap.innerHTML="";routine[day].items.forEach((it,i)=>{const id="ex"+i, card=document.createElement("article");card.className="exercise"+(saved[id]?" done":"");card.innerHTML=`<div class="ex-main"><div class="ex-icon">${it[5]}</div><div class="ex-title"><h3>${it[0]}</h3><div class="chips"><span class="chip">${it[1]}세트</span><span class="chip">${it[2]}</span><span class="chip">휴식 ${it[3]}</span></div></div><input type="checkbox" ${saved[id]?"checked":""}></div><details><summary>자세 / 주의사항</summary><p>${it[4]}</p></details><div class="timer-row">${it[3]!=="-"?`<button data-sec="${parseInt(it[3])}">휴식 ${it[3]}</button>`:""}<button data-log="${it[0]}">기록</button></div>`;$("input",card).onchange=e=>{const s=get(dayKey(),{});s[id]=e.target.checked;set(dayKey(),s);renderWorkout();updateProgress()};const tb=$("[data-sec]",card);if(tb)tb.onclick=()=>startTimer(Number(tb.dataset.sec));$("[data-log]",card).onclick=()=>{route("log");setTimeout(()=>document.querySelector(`[data-name="${CSS.escape(it[0])}"]`)?.scrollIntoView({behavior:"smooth",block:"center"}),60)};wrap.appendChild(card)})}
function updateProgress(){const total=routine[day].items.length, done=Object.values(get(dayKey(),{})).filter(Boolean).length, pct=total?Math.round(done/total*100):0;$("#pctText").textContent=pct+"%";$("#dialFg").style.strokeDashoffset=364.4*(1-pct/100);$("#finishTitle").textContent=pct===100?"MISSION COMPLETE":"MISSION IN PROGRESS";$("#finishSub").textContent=pct===100?"오늘 루틴 완료. 기록 저장까지 하면 완벽해.":"완료 체크를 채우면 오늘 운동이 완료돼."}
function renderLog(){const wrap=$("#logList");wrap.innerHTML="";routine[day].items.forEach(it=>{if(it[3]==="-")return;const name=it[0],d=get("asc.log."+name,{}),card=document.createElement("article");card.className="log-card glass";card.dataset.name=name;card.innerHTML=`<h3>${name}</h3><p class="rec">${rec(d)}</p><div class="setgrid"><input class="kg" type="number" step=".5" placeholder="kg" value="${d.kg??""}"><input class="r1" type="number" placeholder="1" value="${d.r1??""}"><input class="r2" type="number" placeholder="2" value="${d.r2??""}"><input class="r3" type="number" placeholder="3" value="${d.r3??""}"></div><button class="savebtn">저장</button>`;$(".savebtn",card).onclick=()=>{const nd={kg:$(".kg",card).value,r1:$(".r1",card).value,r2:$(".r2",card).value,r3:$(".r3",card).value,date:date()};set("asc.log."+name,nd);$(".rec",card).textContent=rec(nd);navigator.vibrate?.(90)};wrap.appendChild(card)})}
function rec(d){const kg=Number(d.kg), reps=[Number(d.r1),Number(d.r2),Number(d.r3)];if(!kg||reps.some(x=>!x))return"기록하면 다음 무게를 추천해줄게.";if(reps.every(x=>x>=12))return`다음 운동: ${kg+2.5}kg 도전 추천.`;if(reps.every(x=>x>=10))return"같은 무게로 12회까지 채우기.";if(reps.some(x=>x<8))return`무게가 약간 무거움. ${Math.max(kg-2.5,0)}kg도 가능.`;return"현재 무게 유지. 마지막 1~2개 힘든 정도면 적절함."}
function saveWeight(){const w=Number($("#weight").value);if(!w)return;let arr=get("asc.weights",[]).filter(x=>x.date!==date());arr.push({date:date(),weight:w});set("asc.weights",arr.slice(-14));drawChart();navigator.vibrate?.(90)}
function drawChart(){const arr=get("asc.weights",[]), c=$("#chart");if(!arr.length){c.innerHTML='<p class="muted">아침 체중 입력 후 저장하면 그래프가 생겨.</p>';return}const vals=arr.map(x=>x.weight),min=Math.min(...vals)-.5,max=Math.max(...vals)+.5;c.innerHTML="";arr.forEach(x=>{const b=document.createElement("div");b.className="chartbar";b.style.height=20+((x.weight-min)/(max-min))*70+"px";b.innerHTML=`<span>${x.weight}</span>`;c.appendChild(b)})}
function startTimer(sec){clearInterval(tid);remain=sec;$("#timer").classList.add("show");tick();tid=setInterval(()=>{remain--;tick();if(remain<=0){clearInterval(tid);navigator.vibrate?.([250,120,250])}},1000)}
function tick(){const m=String(Math.floor(remain/60)).padStart(2,"0"),s=String(remain%60).padStart(2,"0");$("#timerText").textContent=`${m}:${s}`}
if("serviceWorker"in navigator)navigator.serviceWorker.register("./sw.js").catch(()=>{});
init();
