const routine={1:{ko:"가슴 + 삼두",items:[["인클라인 머신 프레스",4,"8–10",120,"가슴을 높이고 어깨를 뒤로 고정. 팔꿈치 45도.","🏔️"],["체스트 프레스 머신",3,"8–12",120,"어깨가 앞으로 말리지 않게. 팔꿈치 잠금 금지.","⚙️"],["인클라인 덤벨 프레스",3,"8–12",120,"내릴 때 2~3초. 윗가슴 옆으로.","🏋️"],["펙덱 플라이",3,"12–15",60,"수축 지점 1초 정지.","🪽"],["삼두 푸쉬다운",4,"10–15",60,"팔꿈치 고정.","⚡"],["오버헤드 익스텐션",3,"12–15",60,"머리 뒤로 충분히 늘리기.","🔩"]]},2:{ko:"등 + 이두",items:[["친업",4,"가능-1",120,"가슴을 바에 가까이. 광배 늘리기.","🦅"],["랫풀다운",4,"8–12",120,"팔꿈치를 아래로 꽂는 느낌.","⬇️"],["시티드 케이블 로우",3,"10–12",90,"배꼽 방향. 수축 1초.","🚣"],["체스트 서포티드 로우",3,"8–12",90,"가슴 패드 고정.","🧱"],["스트레이트 암 풀다운",3,"12–15",60,"광배로 바를 허벅지까지.","📐"],["덤벨 컬",3,"10–12",60,"팔꿈치 고정.","💪"],["해머컬",3,"10–15",60,"엄지가 위.","🔨"]]},3:{ko:"하체 + 팔",items:[["레그컬",4,"10–15",75,"햄스트링 접기.","🦵"],["레그익스텐션",4,"12–15",75,"상단 1초 정지.","⚙️"],["핵스쿼트",4,"8–10",150,"무릎은 발끝 방향.","🏔️"],["레그프레스",4,"10–12",150,"무릎 잠그지 않기.","🚀"],["루마니안 데드리프트",3,"8–10",150,"엉덩이를 뒤로.","🧲"],["카프레이즈",5,"12–20",60,"아래 끝까지 늘리기.","📈"],["케이블 컬",3,"12–15",60,"이두만.","💪"],["푸쉬다운",3,"12–15",60,"팔꿈치 고정.","⚡"]]},4:{ko:"어깨 + 팔",items:[["머신 숄더프레스",4,"8–10",120,"허리 과신전 금지.","🛡️"],["덤벨 숄더프레스",3,"8–12",120,"귀 옆으로 내리기.","🏋️"],["케이블 레터럴 레이즈",4,"12–20",60,"5kg 힘들면 몸 기울여 한 팔씩.","📡"],["덤벨 레터럴 레이즈",3,"15–20",60,"반동 최소.","🪽"],["리어델트 플라이",4,"12–20",60,"팔꿈치 벌리기.","🎯"],["페이스풀",3,"15–20",60,"눈높이로 당기기.","🧬"],["해머컬",3,"10–15",60,"팔 두께.","🔨"],["오버헤드 익스텐션",3,"12–15",60,"삼두 장두.","🔩"]]},5:{ko:"가슴 + 등 + 팔",items:[["인클라인 머신 프레스",3,"8–10",120,"윗가슴.","🏔️"],["펙덱 플라이",3,"12–15",60,"가슴 수축.","🪽"],["랫풀다운",3,"8–12",120,"광배.","⬇️"],["체스트 서포티드 로우",3,"10–12",90,"등 두께.","🧱"],["프리처 컬",3,"10–12",60,"반동 금지.","💪"],["삼두 푸쉬다운",3,"10–15",60,"끝까지 펴기.","⚡"]]},6:{ko:"어깨 + 하체 + 팔",items:[["덤벨 레터럴 레이즈",4,"15–20",60,"측면 펌핑.","🪽"],["리어델트 플라이",4,"15–20",60,"후면어깨.","🎯"],["레그프레스",4,"10–12",150,"하체 볼륨.","🚀"],["레그컬",3,"12–15",75,"햄스트링.","🦵"],["레그익스텐션",3,"12–15",75,"대퇴사두.","⚙️"],["해머컬",3,"10–15",60,"팔 두께.","🔨"],["오버헤드 익스텐션",3,"12–15",60,"삼두 장두.","🔩"]]},0:{ko:"휴식 / 걷기",items:[["걷기",1,"30–60분",0,"회복 목적.","🚶"],["스트레칭",1,"10분",0,"광배, 고관절, 햄스트링.","🧘"]]}};
const $=(s,r=document)=>r.querySelector(s),$$=(s,r=document)=>[...r.querySelectorAll(s)],today=()=>new Date().toISOString().slice(0,10),get=(k,f)=>{try{return JSON.parse(localStorage.getItem(k))??f}catch{return f}},set=(k,v)=>localStorage.setItem(k,JSON.stringify(v));
let day=Number(get("asc9.day",new Date().getDay())),timerId=null,remain=0,session=get("asc9.session",{active:false,index:0,set:0,resting:false});
const checkKey=()=>`asc9.check.${today()}.${day}`;
function toast(m){const t=$("#toast");t.textContent=m;t.classList.add("show");clearTimeout(window.tt);window.tt=setTimeout(()=>t.classList.remove("show"),1500)}
function vibrate(p=[120]){try{navigator.vibrate?.(p)}catch(e){}}
function xp(n){set("asc9.xp",get("asc9.xp",0)+n)}
function route(id){$$(".tab").forEach(b=>b.classList.toggle("active",b.dataset.tab===id));$$(".page").forEach(p=>p.classList.toggle("active",p.id===id));window.scrollTo({top:0,behavior:"smooth"})}
function profile(){return get("asc9.profile",{name:"민준",birthYear:"2010",height:"",currentWeight:"",goalWeight:"73",bodyFat:"",goalType:"cut",daysPerWeek:"6"})}
function daily(){return get("asc9.daily."+today(),{})}
function saveDaily(o){set("asc9.daily."+today(),{...daily(),...o})}
function ex(){return routine[day].items[session.index]||routine[day].items[0]}
function nextEx(){return routine[day].items[session.index+1]}
function saveSession(){set("asc9.session",session)}
function init(){
 const p=profile(); $("#greet").textContent=(p.name||"민준")+", 오늘도 올라가자";
 ["일","월","화","수","목","금","토"].forEach((n,i)=>{let o=document.createElement("option");o.value=i;o.textContent=`${n} · ${routine[i].ko}`;$("#daySelect").appendChild(o)});$("#daySelect").value=day;
 $("#daySelect").onchange=e=>{day=+e.target.value;set("asc9.day",day);session={active:false,index:0,set:0,resting:false};saveSession();render()};
 $$(".tab").forEach(b=>b.onclick=()=>route(b.dataset.tab));$$("[data-tabgo]").forEach(b=>b.onclick=()=>route(b.dataset.tabgo));
 ["todayWeight","sleep","protein","water"].forEach(id=>{$("#"+id).value=daily()[id]||"";$("#"+id).oninput=()=>{saveDaily({[id]:$("#"+id).value});renderHome();renderAria(false)}});
 ["chkCreatine","chkProtein","chkSkin","chkSteps"].forEach(id=>{$("#"+id).checked=!!daily()[id];$("#"+id).onchange=()=>{saveDaily({[id]:$("#"+id).checked});renderHome();renderAria(false)}});
 ["name","birthYear","height","currentWeight","goalWeight","bodyFat","goalType","daysPerWeek"].forEach(id=>{if($("#"+id))$("#"+id).value=p[id]||""});
 $("#saveProfile").onclick=saveProfile;$("#saveWeight").onclick=saveWeight;$("#saveDay").onclick=saveDay;$("#markToday").onclick=()=>{markDay();toast("오늘 캘린더 체크");render()};$("#clearWeights").onclick=()=>{set("asc9.weights",[]);renderChart();toast("체중 기록 초기화")};
 $("#startSession").onclick=startSession;$("#completeSet").onclick=completeSet;$("#nextExercise").onclick=()=>goNext(false);$("#refreshAria").onclick=()=>{renderAria(true);toast("ARIA 업데이트")};
 $("#saveFood").onclick=saveFood;$("#foodMemo").value=get("asc9.food","");
 $("#savePhoto").onclick=savePhoto;$("#clearPhotos").onclick=()=>{set("asc9.photos",[]);renderPhotos();toast("사진 기록 초기화")};
 $("#sendChat").onclick=sendChat;$("#chatText").addEventListener("keydown",e=>{if(e.key==="Enter")sendChat()});
 render();
}
function saveProfile(){let o={};["name","birthYear","height","currentWeight","goalWeight","bodyFat","goalType","daysPerWeek"].forEach(id=>o[id]=$("#"+id).value);set("asc9.profile",o);if(o.currentWeight&&!daily().todayWeight){$("#todayWeight").value=o.currentWeight;saveDaily({todayWeight:o.currentWeight})}toast("Profile 저장됨");render()}
function saveWeight(){let w=+$("#todayWeight").value;if(!w){toast("체중을 입력해줘");return}saveDaily({todayWeight:w});let arr=get("asc9.weights",[]).filter(x=>x.date!==today());arr.push({date:today(),weight:w});set("asc9.weights",arr.slice(-30));toast("체중 저장됨");vibrate();render()}
function markDay(){let arr=get("asc9.days",[]).filter(x=>x!==today());arr.push(today());set("asc9.days",arr);set("asc9.streak",calcStreak(arr))}
function saveDay(){let w=+$("#todayWeight").value;if(w)saveWeight();markDay();xp(30);toast("오늘 기록 저장됨");render()}
function calcStreak(arr){let s=new Set(arr),n=0,d=new Date();while(s.has(d.toISOString().slice(0,10))){n++;d.setDate(d.getDate()-1)}return n}
function startSession(){session={active:true,index:0,set:0,resting:false};saveSession();toast("세션 시작");vibrate([100]);showTransition("READY",ex()[0]);render()}
function completeSet(){
 if(!session.active){startSession();return}
 if(session.resting){toast("휴식 중이야");return}
 session.set++;xp(2);toast(`${ex()[0]} ${session.set}세트 완료`);vibrate([80]);
 if(session.set>=ex()[1]){let c=get(checkKey(),{});c["ex"+session.index]=true;set(checkKey(),c);setTimeout(()=>goNext(true),250)}
 else startRest(ex()[3]||0);
 saveSession();render()
}
function startRest(sec){if(!sec)return;session.resting=true;saveSession();remain=sec;clearInterval(timerId);tick();timerId=setInterval(()=>{remain--;tick();if(remain<=0){clearInterval(timerId);session.resting=false;saveSession();toast("휴식 끝");vibrate([200,80,200]);render()}},1000);renderSession()}
function tick(){$("#timerBig").textContent=String(Math.floor(remain/60)).padStart(2,"0")+":"+String(remain%60).padStart(2,"0")}
function goNext(auto){
 clearInterval(timerId);session.resting=false;
 if(session.index>=routine[day].items.length-1){session.active=false;saveSession();markDay();toast("오늘 운동 완료");showTransition("MISSION COMPLETE",routine[day].ko);vibrate([180,80,180]);render();return}
 session.index++;session.set=0;saveSession();showTransition("NEXT EXERCISE",ex()[0]);toast(ex()[0]);vibrate([80,40,80]);render()
}
function showTransition(title,sub){$("#transitionTitle").textContent=title;$("#transitionSub").textContent=sub;$("#transition").classList.add("show");setTimeout(()=>$("#transition").classList.remove("show"),850)}
function render(){renderHome();renderWorkout();renderLogs();renderSession();renderFood();renderPhotos();renderChart();renderCalendar();renderAria(false);renderChat()}
function workoutPct(){let total=routine[day].items.length,done=Object.values(get(checkKey(),{})).filter(Boolean).length;return{total,done,pct:total?Math.round(done/total*100):0}}
function renderHome(){let d=daily(),p=profile(),wp=workoutPct(),weight=+(d.todayWeight||p.currentWeight||0),goal=+(p.goalWeight||73),start=+(p.currentWeight||weight||0);$("#currentWeightLabel").textContent=weight||start||0;$("#goalWeightLabel").textContent=goal||0;let gp=0;if(weight&&goal&&start&&start!==goal)gp=Math.max(0,Math.min(100,(start-weight)/(start-goal)*100));$("#goalPct").textContent=Math.round(gp)+"%";$("#goalBar").style.width=gp+"%";$("#goalText").textContent=weight?`목표까지 ${(weight-goal).toFixed(1)}kg`:"체중을 입력해줘.";$("#proteinBar").style.width=Math.min(100,(+d.protein||0)/150*100)+"%";$("#waterBar").style.width=Math.min(100,(+d.water||0)/3000*100)+"%";$("#workPct").textContent=wp.pct+"%";$("#ring").style.strokeDashoffset=389.6*(1-wp.pct/100);let score=Math.round(wp.pct*.35)+Math.min(20,Math.round((+d.protein||0)/150*20))+Math.min(15,Math.round((+d.water||0)/3000*15))+Math.min(15,Math.round((+d.sleep||0)/7*15));["chkCreatine","chkProtein","chkSkin","chkSteps"].forEach(id=>{if(d[id])score+=4});score=Math.min(100,score);$("#score").textContent=score;$("#scoreText").textContent=score>=85?"좋아. 오늘 흐름 좋다.":score>=60?"괜찮아. 부족한 미션만 채우자.":"아직 채울 게 많아.";let x=get("asc9.xp",0);$("#level").textContent=Math.floor(x/100)+1;$("#xpText").textContent=`${x%100}/100 XP`;$("#streak").textContent=get("asc9.streak",0)+"🔥";$("#homeExercise").textContent=session.active?ex()[0]:"운동을 시작해줘";$("#homeSet").textContent=session.active?`${session.set+1}/${ex()[1]}세트 · 다음 ${nextEx()?nextEx()[0]:"완료"}`:"Workout 탭에서 Start Session"}
function renderSession(){let items=routine[day].items;$("#sessionState").textContent=session.resting?"REST":session.active?"NOW":"READY";$("#liveExercise").textContent=session.active?ex()[0]:"Start Session";$("#liveIndex").textContent=session.active?`${session.index+1}/${items.length}`:`0/${items.length}`;$("#liveDetail").textContent=session.active?`${ex()[1]}세트 · ${ex()[2]} · 휴식 ${ex()[3]}초 · ${ex()[4]}`:"Start Session을 누르면 현재 운동 중심으로 진행돼.";$("#nextName").textContent=session.active?`다음 운동: ${nextEx()?nextEx()[0]:"마지막 운동"}`:"다음 운동: -";$("#sessionProgress").style.width=(session.active?(session.index/items.length*100):0)+"%";$("#setDots").innerHTML="";let count=session.active?ex()[1]:3;for(let i=0;i<count;i++){let dot=document.createElement("div");dot.className="dot"+(i<session.set?" done":"");dot.textContent=i+1;$("#setDots").appendChild(dot)}if(!session.active&&!session.resting)$("#timerBig").textContent="00:00"}
function renderWorkout(){let wp=workoutPct();$("#workSummary").innerHTML=`${routine[day].ko} · ${wp.done}/${wp.total} 완료 · ${wp.pct}%`;$("#workoutList").innerHTML="";let checks=get(checkKey(),{});routine[day].items.forEach((it,i)=>{let card=document.createElement("article");card.className="exercise"+(checks["ex"+i]?" done":"");card.innerHTML=`<div class="exTop"><div class="icon">${it[5]}</div><div class="exBody"><h3>${it[0]}</h3><div class="chips"><span class="chip">${it[1]}세트</span><span class="chip">${it[2]}</span><span class="chip">${it[3]}초</span></div></div><input type="checkbox" ${checks["ex"+i]?"checked":""}></div><details><summary>자세</summary>${it[4]}</details>`;$("input",card).onchange=e=>{let c=get(checkKey(),{});c["ex"+i]=e.target.checked;set(checkKey(),c);if(e.target.checked)xp(3);toast(e.target.checked?"운동 체크 완료":"체크 해제");render()};$("#workoutList").appendChild(card)})}
function renderLogs(){$("#logList").innerHTML="";routine[day].items.forEach(it=>{if(it[3]===0)return;let name=it[0],d=get("asc9.log."+name,{}),card=document.createElement("article");card.className="logCard";card.innerHTML=`<h3>${name}</h3><p class="status">${recommend(d)}</p><div class="setgrid"><input class="kg" type="number" step=".5" placeholder="kg" value="${d.kg||""}"><input class="r1" type="number" placeholder="1" value="${d.r1||""}"><input class="r2" type="number" placeholder="2" value="${d.r2||""}"><input class="r3" type="number" placeholder="3" value="${d.r3||""}"></div><button class="btn">저장</button><p class="status">${d.time?`최근 저장 ${d.time}`:"저장 대기 중"}</p>`;$("button",card).onclick=()=>{let nd={kg:$(".kg",card).value,r1:$(".r1",card).value,r2:$(".r2",card).value,r3:$(".r3",card).value,date:today(),time:new Date().toLocaleTimeString("ko-KR",{hour:"2-digit",minute:"2-digit"})};set("asc9.log."+name,nd);xp(8);toast("운동 기록 저장됨");render()};$("#logList").appendChild(card)})}
function recommend(d){let kg=+d.kg,reps=[+d.r1,+d.r2,+d.r3];if(!kg||reps.some(x=>!x))return"기록하면 추천 표시";if(reps.every(x=>x>=12))return`다음 ${kg+2.5}kg 추천`;if(reps.some(x=>x<8))return`${Math.max(0,kg-2.5)}kg로 낮춰도 됨`;return"현재 무게 유지"}
function saveFood(){set("asc9.food",$("#foodMemo").value);$("#foodStatus").textContent="저장됨 · "+new Date().toLocaleTimeString("ko-KR",{hour:"2-digit",minute:"2-digit"});xp(5);toast("Food 저장됨");renderFood();renderHome()}
function renderFood(){let f=get("asc9.food","");$("#foodPreview").textContent=f||"저장된 식단 없음";if(document.activeElement!==$("#foodMemo"))$("#foodMemo").value=f}
function savePhoto(){let file=$("#photoInput").files[0];if(!file){toast("사진을 선택해줘");return}let reader=new FileReader();reader.onload=()=>{let arr=get("asc9.photos",[]);arr.push({date:today(),time:new Date().toLocaleTimeString("ko-KR",{hour:"2-digit",minute:"2-digit"}),memo:$("#photoMemo").value,data:reader.result});set("asc9.photos",arr.slice(-12));$("#photoInput").value="";$("#photoMemo").value="";$("#photoStatus").textContent="저장됨";xp(10);toast("사진 저장됨");renderPhotos();renderHome()};reader.readAsDataURL(file)}
function renderPhotos(){let arr=get("asc9.photos",[]);$("#photoCount").textContent=`${arr.length}개`;$("#photoTimeline").innerHTML=arr.length?"":"저장된 사진 없음";arr.slice().reverse().forEach(p=>{let el=document.createElement("article");el.className="photo";el.innerHTML=`<img src="${p.data}"><div><b>${p.date} ${p.time}</b><p>${p.memo||"메모 없음"}</p></div>`;$("#photoTimeline").appendChild(el)})}
function renderChart(){let arr=get("asc9.weights",[]),c=$("#weightChart");c.innerHTML="";if(!arr.length){c.textContent="체중 저장하면 그래프가 생겨.";return}let vals=arr.map(x=>x.weight),min=Math.min(...vals)-.5,max=Math.max(...vals)+.5;arr.forEach(x=>{let b=document.createElement("div");b.className="chartBar";let h=max===min?60:22+((x.weight-min)/(max-min))*82;b.style.height=h+"px";b.innerHTML=`<span>${x.weight}</span>`;c.appendChild(b)})}
function renderCalendar(){let arr=new Set(get("asc9.days",[])),c=$("#calendar");c.innerHTML="";let d=new Date();d.setDate(d.getDate()-20);for(let i=0;i<21;i++){let iso=d.toISOString().slice(0,10),el=document.createElement("div");el.className="dayDot"+(arr.has(iso)?" done":"");el.textContent=d.getDate();c.appendChild(el);d.setDate(d.getDate()+1)}}
function renderAria(force=false){let d=daily(),p=profile(),wp=workoutPct(),lines=[`운동 완료율 ${wp.done}/${wp.total} (${wp.pct}%)`];if(p.name)lines.unshift(`${p.name} 기준 분석`);if(+d.sleep&&+d.sleep<6)lines.push("수면 부족: 오늘은 실패지점까지 가지 말고 RIR 2 추천.");if((+d.protein||0)<120)lines.push("단백질 부족: 단백질 식사나 프로틴 보충 추천.");if((+d.water||0)<2000)lines.push("수분 부족: 운동 전후 물을 더 챙겨.");if(wp.pct===100)lines.push("오늘 운동 완료. 다음에는 기록 저장까지 하면 좋아.");if(force)lines.push("업데이트 "+new Date().toLocaleTimeString("ko-KR",{hour:"2-digit",minute:"2-digit"}));$("#ariaReport").textContent=lines.join("\n")}
function renderChat(){let arr=get("asc9.chat",[]);$("#chatLog").innerHTML="";arr.forEach(m=>{let div=document.createElement("div");div.className="msg "+m.role;div.textContent=m.text;$("#chatLog").appendChild(div)});$("#chatLog").scrollTop=$("#chatLog").scrollHeight}
function sendChat(){let q=$("#chatText").value.trim();if(!q)return;let arr=get("asc9.chat",[]);arr.push({role:"user",text:q});arr.push({role:"bot",text:answer(q)});set("asc9.chat",arr.slice(-30));$("#chatText").value="";renderChat();toast("ARIA 답변")}
function answer(q){q=q.toLowerCase();if(q.includes("랫풀")||q.includes("풀다운"))return"랫풀다운은 팔로 당긴다기보다 팔꿈치를 아래로 꽂는 느낌이 좋아. 가슴을 살짝 들고, 어깨가 귀 쪽으로 올라가지 않게 해. 3세트 모두 12회가 되면 다음 운동에서 소폭 증량해.";if(q.includes("커팅")||q.includes("다이어트"))return"커팅은 급하게 굶기보다 단백질을 충분히 두고 천천히 감량하는 게 좋아. 현재 앱 기준으로 단백질 130~150g, 물 2.5L 이상, 주당 0.5~0.8kg 감량을 목표로 잡아.";if(q.includes("수면"))return"수면이 6시간 미만이면 고중량 실패지점까지 밀기보다 RIR 2 정도로 남기고, 유산소 강도도 살짝 낮추는 게 좋아.";if(q.includes("프로틴")||q.includes("여드름"))return"여드름이 잘 나면 WPC보다 WPI나 식물성 단백질을 먼저 고려해. 당 많은 매스게이너는 피하는 쪽이 좋아.";if(q.includes("어깨"))return"어깨는 레터럴 레이즈의 볼륨이 중요해. 승모 개입을 줄이고 팔꿈치가 손보다 살짝 높게 간다는 느낌으로 12~20회 범위를 추천해.";return"현재 V9 ARIA는 규칙 기반 베타야. 운동명, 자세, 식단, 수면, 프로틴처럼 구체적으로 물어보면 더 정확히 도와줄게."}
if("serviceWorker"in navigator)navigator.serviceWorker.register("./sw.js").catch(()=>{});
document.addEventListener("DOMContentLoaded",init);
